### ISSUE TITLE
Firefox: input field overflow bug

### ISSUE THREAD

**Issue by jorgenboganes** [Adyen/adyen-web#1989] opened 2023-02-14 07:17 UTC
**Describe the bug**
In next.js-apps, the input field (e.g. the credit card details) have a scrollable body. The html tag for the iframe should probably set the overflow property to "hidden"

**To Reproduce**
1. `npx create-next-app@latest`
2. `npm install @adyen/adyen-web`
3. Set up a session and mount the checkout div as explained in Adyen docs
4. Scroll in input fields

**Expected behavior**
Input fields should act as text inputs, not as <html> pages with `overflow:scroll`

**Screenshots**
![gif](https://i.imgur.com/YpUS96g.gif)

**Desktop (please complete the following information):**
 - Device: Macbook Pro 16" 2019
 - OS: macOS Monterey 12.3.1
 - Browser: Firefox
 - Version: 109.0.1

**Smartphone (please complete the following information):**
Doesn't happen on smartphones

**Comment by m1aw** [comment] 2023-02-14 12:09
Hey @jorgenboganes 

I don't think this is a issue since it's only happening with Firefox on responsive mode.
That being said, could you provide a code sample for this (stackblitz, or similar)?
I have the feeling it would be related to next.js and would like to take a look.

Thank you.

**Comment by m1aw** [comment] 2023-02-21 13:28
Hey @jorgenboganes 

Thanks for the report, we where able to reproduce the issue. We are going to fix it in the coming versions.

**Comment by sponglord** [comment] 2023-03-14 12:24
@jorgenboganes - this should be fixed with release `5.35.0`.

**Closed** 2023-04-04 13:00 UTC
Labels: Bug report, Fixed: awaiting confirmation
