### ISSUE TITLE
```directEbanking```: The passed payment method is not a valid Checkout Component

### ISSUE THREAD

**Issue by Seif-apprentus** [Adyen/adyen-web#1561] opened 2022-04-05 12:12 UTC
**Describe the bug**
```directEbanking``` payment method is not in version 5.12.0, and I got a message: The passed payment method is not a valid Checkout Component.

**To Reproduce**
checkout.create('directEbanking').mount(sofort.current)

**Expected behavior**
The component should appear on the page.

**Additional context**
```directEbanking``` is Ok with adyen-web version 5.2.2 so what happens in version 5.12? Is it under another name (not ```directEbanking``` any more)

**Comment by Seif-apprentus** [comment] 2022-04-08 10:36
@ribeiroguilherme  Thank you for the feedback, it would be great if you include the component in the playground.
Thank you!

**Comment by ribeiroguilherme** [comment] 2022-04-08 12:55
@Seif-apprentus Did you manage to fix your issue? 

The component could be added to the playground on the [Components.js](https://github.com/Adyen/adyen-web/blob/master/packages/playground/src/pages/Components/Components.js) file. I am not sure if it helps with something though! This payment method is very straight forward and does not require any special configuration :-)

**Comment by Seif-apprentus** [comment] 2022-04-08 17:38
@ribeiroguilherme Yes, I solved the issue! Thanks :)
I mean what about adding to the playground all Adyen components in the documentation of Adyen's website so that some beginners could navigate them all :)

**Comment by atty31** [comment] 2022-05-25 10:06
Is there any new updates on this issue? I m getting the same js error for bank transfer: 
![Screenshot(139)](https://user-images.githubusercontent.com/3530315/170237746-69bec335-0391-4a3c-bd1c-a2e8385d2c75.png)
Thanks

**Comment by tgachet** [comment] 2022-06-08 08:54
Hello, 

I encounter the same issue as described at the top of this topic
![image](https://user-images.githubusercontent.com/22431057/172575203-921a80ed-d495-4078-a8c2-25405b38a7e6.png)

I'm using the latest version with `v68/sessions` (as describe here https://docs.adyen.com/online-payments/web-components) . I have no problem with other payment methods (e.g `cards` or `giropay`). 

@ribeiroguilherme can you provide a more detailed response about the setup API call ? I don't see any paymentMethods object when using `/sessions` (https://docs.adyen.com/api-explorer/#/CheckoutService/v68/post/sessions)
> If you are using /sessions, then check if the setup API call contains the directEbanking payment method inside the paymentMethods object


@Seif-apprentus how did you manage to solve the issue ?

Thank you

**Comment by ribeiroguilherme** [comment] 2022-10-04 11:47
Closing this ticket as the issue is solved. Feel free to reach out in case of any other issues. Cheers!

**Closed by ribeiroguilherme** 2022-10-04 11:47 UTC
Labels: Bug report, Needs more info
