### ISSUE TITLE
Dropin does not display error message 

### ISSUE THREAD

**Issue by AndreaGhisa1** [Adyen/adyen-web#1462] opened 2022-01-25 12:19 UTC
**Describe the bug**
If we enter a wrong CVV for a stored payment method the error message is not displayed (we set in code dropin.setStatus('error').
From our investigation, it seems the drop-in is reinitialized (onReady method is called again). In the screenshot below you can see how the drop-in looks like after we set the status to error:
![image](https://user-images.githubusercontent.com/97953166/150971764-a7996cc2-09a7-4c59-89f9-f28e369af8a1.png)
![image](https://user-images.githubusercontent.com/97953166/150990493-8942b248-4ee9-45eb-be45-2a36e43411a1.png)

**The class added is "__dropin--ready" instead of "adyen-checkout__status adyen-checkout__status--error".**

The flow is as follows when we click "Save" the loading icon appears :
![image](https://user-images.githubusercontent.com/97953166/150990168-5d6ae95e-5ccd-497d-9814-5660c0d4b30d.png)
![image](https://user-images.githubusercontent.com/97953166/150990927-c1808686-38d4-441b-bdbc-e2bded518881.png)

After backend validation, we set the error status to drop-in. At that point, the onReady method is called again automatically. 
In the UI: 
1. The stored payment method remains there with the CVV already filled.
2. Loading button became "Save" button again.

Based on the documentation we create the drop in as follows:
```
            const checkout = await AdyenCheckout(configuration);
            dropin = checkout.create('dropin', {
                onReady: () => {
                    console.log('Dropin was initialized');
                    }
                }
            }).mount('#dropin-container');
```
**This problem does not occur in 3.10.1 drop-in version**. We just updated the Nuget package to 8.0.1 and drop-in to version 5.3.1 and we saw that the validation is not working properly anymore.

**Expected behavior**
The error message should be displayed in the drop-in when
![image](https://user-images.githubusercontent.com/97953166/150971812-324ba683-59d2-4c9a-b2de-68ec49b9ee92.png)

**Additional context**
Adyen NuGet version 8.0.1
Web Components/Drop-in v5.3.1

**Comment by ribeiroguilherme** [comment] 2023-02-07 12:05
Closing this issue as we can't reproduce the problem. Please reach out to support if the problem persists. Cheers

**Closed by ribeiroguilherme** 2023-02-07 12:05 UTC
Labels: Needs more info
