### ISSUE TITLE
Placeholder text is not vertically centered when using a custom font

### ISSUE THREAD

**Issue by jessplkane** [Adyen/adyen-web#2593] opened 2024-03-08 13:40 UTC
**Describe the bug**
When passing a custom fontFamily using the Cards Web Drop-in integration, the placeholder text for the card inputs is not vertically centered on Chrome or Firefox. When the default font is used, this issue is not present.

**To Reproduce**
1. Pass a styles object to the Web Drop-in as described [here](https://docs.adyen.com/payment-methods/cards/custom-card-integration/#styling), where the fontFamily is a custom font defined in your project using .woff files
2. Load the Web Drop-in and see that the font is not vertically aligned

**Expected behavior**
I would expect the placeholder text to remain vertically centered in the card inputs, regardless of the font family used.

**Screenshots**
Screenshot showing input with default font family:
![Screenshot 2024-03-08 at 12 24 44](https://github.com/Adyen/adyen-web/assets/25350840/15b3155e-43b1-4013-bc7e-f7bf5ce85b71)

Screenshot showing input when custom fontFamily is passed into styles object
![Screenshot 2024-03-08 at 12 25 49](https://github.com/Adyen/adyen-web/assets/25350840/cb2fa0ec-29f6-47a6-9286-8fddd30c6f74)

**Desktop (please complete the following information):**
 - OS: Sonoma 14.3.1
 - Browser: Chrome v122, Firefox v122 (screenshots are from Chrome)
Couldn't reproduce this issue on Safari

**Smartphone (please complete the following information):**
Couldn't reproduce this issue on mobile

**Additional context**
N/A

**Comment by sponglord** [comment] 2024-03-12 12:09
Hi @jessplkane - I don't know what exactly is happening with the alignment of the text, but we don't support passing a custom font in the styles configuration for these fields. From the screenshot it looks like the font is defaulting to a system serif font, which is expected behaviour.
I would like to understand what is happening though. How are you setting this custom font? As a url or a encoded blob?
Can you share the styles config you are using - I'd at least like to know what is going on with the vertical alignment

**Comment by sponglord** [comment] 2024-04-22 13:26
There's been no reply for 5 weeks - so I'm closing this ticket.

**Closed by sponglord** 2024-04-22 13:26 UTC
Labels: Needs more info
