### ISSUE TITLE
'stateOrProvince' field is not prefilled after a failed transaction

### ISSUE THREAD

**Issue by StaryFritz** [Adyen/adyen-web#2832] opened 2024-09-03 17:34 UTC
**Describe the bug**
'stateOrProvince' field is not prefilled using the autocomplete functionality in the checkout component after a failed transaction

**To Reproduce**
1. Open the 'checkout' page;
2. Fill in the mandatory card fields;
3. Select an address using the search and autocomplete functionalities;
4.Cause the transaction to fail;
5. Search for the previous address again.

**Expected behavior**
The 'stateOrProvince' field is prefilled.

https://jam.dev/c/5cd2abf8-6f86-4d22-aba7-e80a3f488216

**Comment by m1aw** [comment] 2024-10-16 09:54
Hello @StaryFritz 

Indeed this seems like a bug. We will pick this up soon and release a fix in the next few release.

Thanks for the report.

**Comment by ribeiroguilherme** [comment] 2024-10-31 13:37
Hey @StaryFritz - we made a release containing the fix for it. Can you please check if that fixes your issue?

**Comment by ribeiroguilherme** [comment] 2024-11-13 09:48
Closing this issue since the problem is fixed on 6.5.0. If the problem persists, please create another issue. Cheers

**Closed by ribeiroguilherme** 2024-11-13 09:48 UTC
Labels: Needs more info, Fixed: awaiting confirmation
