### ISSUE TITLE
Click to pay card image size can have invalid size in some cases

### ISSUE THREAD

**Issue by tlenclos** [Adyen/adyen-web#2605] opened 2024-03-19 09:31 UTC
**Describe the bug**
Click to pay card image size  can have invalid size in some cases.
Not sure it is really an issue but IMO Adyen components should be as precise as possible regarding image size to avoid these conflicts, just like other adyen images are.

**To Reproduce**
1. Have a userland css like so
```css
img {
    height: auto;
}
```

2. Activate click to pay on Adyen dropin
3. See card size overflow

**Expected behavior**
Images should have fixed size with CSS to avoid conflicting with userland CSS as much as possible.

See https://github.com/Adyen/adyen-web/blob/3ce12ef069ba39c4ae9c5f794261f5bbffb87e9a/packages/lib/src/components/internal/ClickToPay/components/CtPCards/CtPSingleCard/CtPSingleCard.scss#L27

**Screenshots**
<img width="732" alt="image" src="https://github.com/Adyen/adyen-web/assets/686101/69eec96a-b6b0-45d3-a9cc-2e104fd73f87">

**Comment by ribeiroguilherme** [comment] 2024-03-19 12:13
Hi @tlenclos ,

Are you able to reproduce this on [https://](https://www.mystoredemo.io/#/) ? You can try to recreate by adding a item to the cart, then go to Checkout page, click on `I want to have Click to Pay as a payment method option` checkbox, enter your test email and proceed to the Checkout. Then click in the Card component and you should be able to test CTP.

I can't reproduce myself nor heard of any merchant facing this. I believe your CSS in your web app is overriding the Adyen styles.

**Comment by tlenclos** [comment] 2024-03-19 13:07
Yes we do have a global CSS with these rules, this also why I wrote "some cases" since it's our specific case and I was not sure if it could be an issue for everyone using the dropin. This is the only image we encounter without a size defined in CSS, only in html attribute, so it is overwritten by a global rule like this.

```
img {
    height: auto;
}
```

**Comment by ribeiroguilherme** [comment] 2024-03-26 12:50
Hey @tlenclos ,

I see on your screenshot that in your use-case you have a single test card, and for this scenario we explicitly set the height to 24px in the HTML img markup (you can verify that in the mystoredemo website). So , I assume in this case your CSS rules are impacting the image sizes behavior. This is something out of our control, and needs to be adjusted on your side.

I will close the issue then, and thanks for reaching out anyway. Cheers!

**Closed by ribeiroguilherme** 2024-03-26 12:50 UTC
