### ISSUE TITLE
Card holder name is validated by client side scripts instead of Adyen due to 'required' attribute in code

### ISSUE THREAD

**Issue by johns-abraham-borngroup** [Adyen/adyen-web#1452] opened 2022-01-18 12:32 UTC
**Describe the bug**
We are getting an odd error message for card holder name field.

When we set card holder name (holderNameRequired = true) the Card Holder name input field is rendering with 'required' attribute unlike card number field, cvv field, expiry date field etc.
Due to this 'required' attribute the client side code dong a validation on that required field even before Adyen does the same.

Please note that, if we remove the 'required' attribute it will work as expected.

**To Reproduce**
Enabled Card holder name from BM, set holderNameRequired = true

**Expected behavior**
The field should be validated by Adyen instead of client side scripts since its coming from Adyen, 

**Screenshots**
![image](https://user-images.githubusercontent.com/77099234/149937764-20e8a273-efbf-4d1e-a825-b7a9632a6092.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 97

**Additional context**

**Comment by johns-abraham-borngroup** [comment] 2022-01-20 08:53
Comparison image with and without 'required' attribute.
![image](https://user-images.githubusercontent.com/77099234/150304641-8d91f01d-07db-4098-a8ff-75dbfb9295e8.png)

**Comment by ribeiroguilherme** [comment] 2022-01-24 12:32
Hi @johns-abraham-borngroup ,

Thanks for reaching out. Can you share what version are you using? I did a quick test on the latest release and on (https://www.mystoredemo.io/)[MyStore demo] and I didn't manage to reproduce this issue.

**Comment by AndreaGhisa1** [comment] 2022-02-16 13:46
Hi @ribeiroguilherme,
We also have a problem with the cardholder name we are using version **5.3.1** (we cannot update to the latest version released because of another bug reported https://github.com/Adyen/adyen-web/issues/1426).

We observed that after the drop-in is loaded if you click on the cardholder name and change the focus on another element following message appears **"Invalid cardholder name"**.

Steps to reproduce:
1. Make sure you configure the option "holderNameRequired": true:
```
  paymentMethodsConfiguration: {
                    card: {
                        hasHolderName: true,
                        holderNameRequired: true
                    }
                }
```
2. When the drop-in appears click on the cardholder name field.
3. Click on the region above the input (See screenshot)
![image](https://user-images.githubusercontent.com/97953166/154277063-7335368d-2408-4f89-bec8-8f62b9c95ca7.png)

Following message appears:
![image](https://user-images.githubusercontent.com/97953166/154277215-c180a889-2bb8-4679-ad87-e5590e6c19c2.png)

**Expected result**
Validation should appear only when the user clicks on the "Save" button.
![image](https://user-images.githubusercontent.com/97953166/154277382-58c08614-7a05-48d4-b7a7-2778ba4cf909.png)

**Comment by ribeiroguilherme** [comment] 2022-02-18 16:14
@AndreaGhisa1 we are currently discussing various issues with UX/design team including how/when fields are validated and we'll get back to you

**Comment by sponglord** [comment] 2022-09-20 09:58
I am closing this issue since I believe it has been addressed in later releases. If you still think this issue persists please make a new ticket

**Closed by sponglord** 2022-09-20 09:58 UTC
Labels: Bug report, Progress: on hold

**Comment by Arootin** [comment] 2022-09-23 13:34
To whoever may run into this problem:
It's mainly caused by the fact that you are using a `form` to submit data to adyen. The `required` field prevents the form from being submitted and Adyen validation to trigger.
The solution is to just add the `noValidate` attribute to your form and Adyen will take care of the rest.
