### ISSUE TITLE
Angular SSR: ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by drafenous** [Adyen/adyen-web#1315] opened 2021-10-07 21:36 UTC
**Describe the bug**
I'm trying to enable SSR on my Angular project with SAP Spartacus, but when i instance with 'new AdyenCheckout(config)' and enable Angular Universal SSR, then crashes with message:
ReferenceError: Element is not defined

**To Reproduce**
Implement Angular Universal SSR on project.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/8341200/136464907-623b145c-88b5-43c8-ab00-e81a6e5cdca6.png)
If uncomment the line 151, then crashes.

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser: Chrome 94
 - Node Version: 12.22.1
 - Npm Version: 6.14.12
 - Package Version: "@adyen/adyen-web": "^4.7.3",
 - Angular Version: 10.2.3

**Additional context**
I tryed to isolate with isPlatformBrowser() from '@angular/common' and make a conditional import of component, but no success.

**Comment by ribeiroguilherme** [comment] 2021-10-14 09:42
Hi @drafenous 

Thanks for reaching out. Apparently the issue is that Angular Universal is executed in the server, therefore some of the browser APIs and capabilities might be missing there, like the `window`, `document`, `navigator`, etc. And `adyen-web` interacts with some of these API's. This can be the reason why you get this error.

You can read more about it here: 
https://angular.io/guide/universal#working-around-the-browser-apis

As it states in the docs, Angular provides some abstractions for `Location` and `Document` browser API's. But you still need to go around and adapt it for the `window` object. There is a blog post here that might be useful: http://michaelborisov.com/blog

I'll close this ticket, but feel free to reopen if you think this is still an issue related to this library.

Hope this helps!

**Comment by drafenous** [comment] 2021-10-29 18:16
Sorry for the delay, lost a busy week with the first release of our ecommerce.

We've tried so far:
- Isolate the intantiation of AdyenCheckout(this.configuration) validating with isPlatformBrowser, but without success. Below is an example.

![image](https://user-images.githubusercontent.com/8341200/139482999-f5f4b656-f3b3-4872-9828-2c0efb76c347.png)
...

![image](https://user-images.githubusercontent.com/8341200/139483044-fcc2a8dc-9979-4d06-aaaa-2d19985f997b.png)


- Isolating the SSR checkout URL, but unsuccessfully, I believe this is due to the fact that the problem is generated during the build and not during route requests... Still we think it would be a valid test, but without success.

- Using the domino lib, which can emulate the Window, Document and others variable, including the Element variable, but somehow we were not successful either.

- We were informed that when using the domino lib, we have to declare the variables before importing the AppServerModule into server.ts, we also tried it but without a solution.

We think it's something related to Adyen, because when removing the AdyenCheckout import and instantiation from the component it doesn't show any more errors.

Our frontend project is being built using storefront SAP Spartacus 3.4, Angular 10.2.4, Node 12.22.1, npm 6.14.12 and TypeScript 4.0.7.

Here's our updated server.ts file.

```JS
/***************************************************************************************************
 * Load `$localize` onto the global scope - used if i18n tags appear in Angular templates.
 */
import '@angular/localize/init';
import 'zone.js/dist/zone-node';

const domino = require('domino');
const fs = require('fs');
const path = require('path');
const template = fs.readFileSync(path.join(join(process.cwd(), 'dist/spartacus/browser'), 'index.html')).toString();
Object.assign(global, domino.impl);
// tslint:disable-next-line: no-string-literal
(global as any)['Element'] = domino.impl.Element;
const win = domino.createWindow(template);
// tslint:disable-next-line: no-string-literal
global['window'] = win;
// tslint:disable-next-line: no-string-literal
global['document'] = win.document;

import { ngExpressEngine as engine } from '@nguniversal/express-engine';
import { NgExpressEngineDecorator } from '@spartacus/setup/ssr';
import * as express from 'express';
import { join } from 'path';

import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';

import 'localstorage-polyfill';
/* tslint:disable-next-line no-string-literal */
global['localStorage'] = localStorage;

const ngExpressEngine = NgExpressEngineDecorator.get(engine);

import { AppServerModule } from './src/main.server';
// The Express app is exported so that it can be used by serverless Functions.
// tslint:disable-next-line: typedef
export function app() {
  const server = express();
  const distFolder = join(process.cwd(), 'dist/spartacus/browser');
  const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';

  server.engine(
    'html',
    ngExpressEngine({
      bootstrap: AppServerModule
    })
  );

  server.set('view engine', 'html');
  server.set('views', distFolder);

  // restrict folders
  server.get('/checkout/**', (req, res) => {
    res.sendFile(join(distFolder, 'index.html'));
  });

  // Serve static files from /browser
  server.get(
    '*.*',
    express.static(distFolder, {
      maxAge: '1y'
    })
  );

  // All regular routes use the Universal engine
  server.get('*', (req, res) => {
    res.render(indexHtml, {
      req,
      providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }]
    });
  });

  return server;
}

// tslint:disable-next-line: typedef
function run() {
  const port = process.env.PORT || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    // tslint:disable-next-line: no-console
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

// Webpack will replace 'require' with '__webpack_require__'
// '__non_webpack_require__' is a proxy to Node 'require'
// The below code is to ensure that the server is run only when not requiring the bundle.
declare const __non_webpack_require__: NodeRequire;
const mainModule = __non_webpack_require__.main;
const moduleFilename = (mainModule && mainModule.filename) || '';
if (moduleFilename === __filename || moduleFilename.includes('iisnode')) {
  run();
}

export * from './src/main.server';
```

**Comment by ribeiroguilherme** [comment] 2021-11-04 16:59
@drafenous, did you try to force the load of module/component that uses the library on the client side instead of loading it in the server?

I am aware that you are using Angular SSR, but for example, using Next.js framework you can force the load of a specific module on the client side (https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr). Can you try a similar approach in your Angular app?

There were other issues in the past related to SSR which were fixed by dynamic imports. Please have a look, they might help you. #902 #233

**Comment by drafenous** [comment] 2021-11-04 19:41
This semantics is not possible in Angular 10.
However, we took a new approach to dynamic import that we found ended up working.
Here is our validation if it is of interest to you:

```JS
          if (this.isBrowser) {
            import('@adyen/adyen-web').then(module => {
              this.checkout = new module.default(this.configuration);
              this.changePaymentMethod(null, 'creditcard');
            });
          }
```

**Closed** 2021-11-04 19:41 UTC

**Comment by ribeiroguilherme** [comment] 2021-11-05 08:35
I am aware that Next.js syntax isn't possible in Angular 10, but I meant about the approach that they did, using dynamic imports.

I'm glad that dynamic imports worked for you, and thanks for sharing your solution. It might help others.

**Comment by jonlambert** [comment] 2021-11-23 15:57
Hey @ribeiroguilherme - totally understandable that Adyen wouldn't choose to support SSR for this library. But I would say that this is one of the very few libraries that crash loudly just when importing on the server-side, instead of gracefully recognising a server environment and halting any execution - or failing when actually using the library. Dynamic importing is a doable workaround, but this complicates things when using TypeScript.

I've no idea of the complexity of implementing such a thing, but it would be significantly easier if we could import AdyenCheckout then check if window is defined (or similar check) before instantiating.

**Comment by ribeiroguilherme** [comment] 2021-11-24 10:53
@jonlambert thanks for your input. That is a very good suggestion, and we would like to have a look into it. 

Do you know by any chance examples of libraries that halt the execution in the server environment gracefully? So we can investigate properly how they perform those checks and try to find a good fit for our case.

**Comment by jonlambert** [comment] 2021-11-24 12:07
No worries! That would be great. 

So you could early-exit and expose some stub methods for code running in SSR, but that's probably a sledgehammer to crack a nut. The problem can usually be avoided by removing any code that expects a browser environment, executing at the top level of a file (outside classes or functions). I can't test this as the problem doesn't seem to appear when building this library locally, but this line looks like it's trying to access `Element.prototype`:

https://github.com/Adyen/adyen-web/blob/9430ca6ed9aeff69f15d03258088fd57a1ae041c/packages/lib/src/polyfills.ts#L26

...which might explain the error we're getting above.

Quick fix might be to wrap that in a conditional, checking for the presence of `Element`, `CharacterData` and `DocumentType`!

**Comment by ribeiroguilherme** [comment] 2021-11-24 15:24
@jonlambert this file (`polyfills.ts`) is going to be removed on #1343, which is about to be merged quite soon. It will most likely fix the error that was pointed out on this issue 👍

**Comment by jonlambert** [comment] 2021-11-24 16:48
@ribeiroguilherme Ah that's great to hear 🙂 I managed to get a dev setup working and debugged the issue further. Turns out there are a few other parts of the codebase that access `window` at the top level. I've updated #1384 to add presence checks before using, and can now include the library on my machine without SSR blowing it up 🙂

**Comment by theazgra** [comment] 2022-01-21 10:00
Same problem for Nuxt with Vue 2.
@drafenous Solution worked. 
`await` can't be used tho, only the `.then` syntax.
