### ISSUE TITLE
ApplePay not working - Required field 'merchantIdentifier' is null always

### ISSUE THREAD

**Issue by alexandrebrubeyonds** [Adyen/adyen-web#1850] opened 2022-11-19 09:47 UTC
**Describe the bug**
Apple Pay merchant name and Apple Pay merchant identifier is well configured.
But when we click on Apple Pay Button, the ajax get request respond error.

Request : https://checkoutshopper-live.adyen.com/checkoutshopper/v1/applePay/sessions?clientKey=XXXXXX
Response : 
`{
    "status": 500,
    "errorCode": "702",
    "message": "Required field 'merchantIdentifier' is null",
    "errorType": "validation"
}`

I try to add merchantIdentifier in queryString, but response is the same.
  
**To Reproduce**
1. Setup Apple Pay
2. Click on 'Apple Pay Button' to pay
3. See error in console

**Comment by ribeiroguilherme** [comment] 2022-12-02 14:43
Hey @alexandrebrubeyonds .

Does this issue happens in 'test' or only 'live' ? What version of the SDK are you using?

**Comment by alexandrebrubeyonds** [comment] 2022-12-07 09:57
Both, I use de PrestaShop plugin : https://github.com/Adyen/adyen-prestashop

**Comment by ribeiroguilherme** [comment] 2022-12-15 12:27
Seems to me that the issue is related with how the PrestaShop plugin is integrating with our SDK - maybe it is not properly populating the required parameters. Can you reach out to them? Thanks

**Comment by francoispeyret** [comment] 2023-01-12 16:09
@alexandrebrubeyonds
hello, we encounter the same error in version 4.0.0 on a PrestaShop 1.7.7.2.
Did you find a solution ?

Thank you in advance.

**Comment by ribeiroguilherme** [comment] 2023-01-18 09:10
Closing as it is not related to this repo. Issue can be followed up [here](https://github.com/Adyen/adyen-prestashop/issues/252).

**Closed by ribeiroguilherme** 2023-01-18 09:10 UTC
Labels: Needs more info
