### ISSUE TITLE
Production build not working with @adyen/adyen-web/auto

### ISSUE THREAD

**Issue by tlenclos** [Adyen/adyen-web#2818] opened 2024-08-28 13:59 UTC
**Describe the bug**
Hello ! We are in the process of migrating the library from 5.59.0 to 6.1.0 and we use Vite to build our project.

It seems that the `@adyen/adyen-web/auto` export doesn't work as expected since we encounter these messages when running the production build and the Dropin does not show : 
> Dropin: You support the payment method 'scheme' but this component has not been configured. Make sure to import the Class  'Card' and then pass it in the Dropin's 'paymentMethodComponents' config property if you wish to offer this payment method.

It works fine with the dev server.

**To Reproduce**
1. Build an app with vite and use `@adyen/adyen-web/auto`
2. Mount dropin with just payment methods configurations
```tsx
import { AdyenCheckout, CoreConfiguration, Dropin, DropinConfiguration } from '@adyen/adyen-web/auto';

const paymentMethodsConfiguration: DropinConfiguration['paymentMethodsConfiguration'] = {
    card: {
        autoFocus: true,
        enableStoreDetails: true,
        hasHolderName: process.env.REACT_APP_ADYEN_HOLDER_NAME === 'true',
    },
};

new Dropin(checkout, {
    paymentMethodsConfiguration,
}).mount(container.current);
```

**Expected behavior**
Dropin should show.

**Additional context**
-  "vite": "^5.1.6"
- "@adyen/adyen-web": "6.1.0"

**Comment by ribeiroguilherme** [comment] 2024-08-29 10:56
Hey @tlenclos ,

Can you by any chance provide a reproducible example and share with us? That would be the easiest way for us to investigate. Perhaps create a minimal Github repo with your setup, which we can build and start a local server serving the static files (no need to make APi calls, those can be mocked). Otherwise it is hard to troubleshoot this.

We have tested the `auto` on production build and it seem ok. We have an example using Nextjs which you can run the production build locally, and it works fine. (you can try it out [here](https://github.com/Adyen/adyen-web/tree/main/examples/nextjs).

Can you also tell me what do you get when you run `window.AdyenWebMetadata` in the browser console using your prod version?

**Comment by tlenclos** [comment] 2024-09-06 15:12
I'll see if I can make a reproducer.

In the meantime, I got this when running `window.AdyenWebMetadata` :

```js
{
    "version": "6.1.0",
    "bundleType": "eslegacy"
}
```

We are not using Next.js, just Vite with an SPA app. Even though we are importing like so :

For example I had to add Twint and setup it manually in order to display it, and we need automatic setup without explicitely requiring payment methods.

```diff
import {
    AdyenCheckout,
    CoreConfiguration,
    Dropin,
    DropinConfiguration,
+   Twint,
} from '@adyen/adyen-web/auto';

...

new Dropin(checkout, {
  paymentMethodComponents: [Twint],
  paymentMethodsConfiguration,
}).mount(container.current);
```

**Comment by ribeiroguilherme** [comment] 2024-09-09 09:41
It seems like the module resolution mechanism of your application is ignoring the 'auto' bundle path and doing the fallback to the 'eslegacy' bundle type, which is usually used with setups that are using Webpack 4 for example. By seeing the "eslegacy" , I can tell that the "auto" mode is not being loaded indeed.

You mentioned Vite with an SPA - can you elaborate a bit more on this setup? Are you using Webpack 4 by any chance or any other bundler? This SPA - how was it generated?

I'd like to help you here and investigate this further, but it is hard without having an reproducible repo with the proper dependencies that you are using.  Do you think it is possible to provide a bare minimum project skeleton with the project dependencies, so we can take a closer look into it? No need to implement any code into it - just scaffold a repo that contains your dependencies and make sure that the web app starts when running `npm start` should be enough.

**Comment by jellevdv** [comment] 2024-09-18 07:35
We're running into the same issues using Lit (no webpack, only Rollup and Babel) 
We "fixed" the issue using the following hack
```
import { AdyenCheckout, Dropin, ICore, DropinConfiguration, CoreConfiguration, **components** } from '@adyen/adyen-web';

private get dropinConfiguration(): DropinConfiguration
    {
        // Used because the auto import does not work!
        // We have to map all these components to add them instead of relying on Adyen
        const { ...Components } = components;
        const Classes = Object.keys(Components).map(key => Components[key]);
        AdyenCheckout.register(...Classes);
        return {
            onSelect: () => { this.fireEvent('paymentmethodselect'); },
            openFirstPaymentMethod: true,
            paymentMethodComponents: Classes as never[],
            paymentMethodsConfiguration: {...}
        };
    }
```

**Comment by bramdebouvere** [comment] 2024-09-18 07:36
We also had the same issue in an Open-WC project (Lit + rollup + babel).

For now we worked around by importing the components from @adyen/adyen-web instead.
`import { components } from '@adyen/adyen-web';`

And in the function where we create our Dropin Configuration, we register the classes similar to how it's done in the "auto" import:
`const { ...Components } = components;`
 `const Classes = Object.keys(Components).map(key => Components[key]);`
 `AdyenCheckout.register(...Classes);`

**Comment by jellevdv** [comment] 2024-09-18 07:42
Same issue here, the components don't seem to load using the /auto import 😥
We also used the same hack as above to fix the issue, we do have a fixed list of payment methods but can't seem to find there correct components for all of them, as the mapping is not 1:1.
Payment methods like UnionPay or JCB don't seem to be in the following components list https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/components/index.ts

**Comment by ribeiroguilherme** [comment] 2024-09-18 12:21
@tlenclos here is a code repo using Vite 5.1.6 with the auto package with some mocked payment methods: https://stackblitz.com/edit/vitejs-vite-w7iztm?file=main.js - can you let me know if I am missing something?

@bramdebouvere could you provide a small reproducible example (same as I shared above using 'stackblitz'), so we can have a look? That would be very helpful

@jellevdv can you share more details about your setup - which framework/bundler is involved? it would be great too if you can provide an example for us. 
Regarding the payment methods that are not available in the list: most likely they are Redirect payment methods. We do not expose specific Components for Redirects. 
They must be created by doing `new Redirect(checkout, { type: 'my-payment-type'});`

**Comment by sponglord** [comment] 2024-09-18 12:26
@jellevdv More specifically `UnionPay (SecurePay / UPOP)` is a deprecated paymentMethod. Instead you shoudl be offering `UnionPay (CUP)` via the card component instead.
Likewise `JCB` can also be offered via the Card component.
In Essence both UnionPay(Cup) and JCB are card brands that, if configured in the Adyen CustomerArea, will show up as supported brands when you present a Card component

**Comment by ribeiroguilherme** [comment] 2024-09-30 08:18
@bramdebouvere here is an example using Open-WC project (Lit + rollup + babel): https://stackblitz.com/edit/openwc-lit-rollup-babel?file=src%2Fadyen-v6-demo.js - can you let me know what is missing in this case? The 'auto' seems to work as expected  (once the dev server starts, it will take couple of seconds to render the UI)

**Comment by tlenclos** [comment] 2024-10-03 09:40
@ribeiroguilherme yes in development mode it works properly, the issue is only in production with the build.

**Comment by ribeiroguilherme** [comment] 2024-10-03 14:54
@tlenclos thanks for checking it out. I missed the detail that it was impacting only prod build. I will take further look.
@bramdebouvere does the same apply for your case?

**Comment by tlenclos** [comment] 2024-10-17 07:41
Hello @ribeiroguilherme, did you look into this issue again ? Let me know if I can be of any help. It's blocking us to upgrade to V6 for now.

**Comment by bramdebouvere** [comment] 2024-10-17 14:13
@ribeiroguilherme Sorry that I have not found the time to look at this yet. I'll try to free up some time soon.

**Comment by tlenclos** [comment] 2024-10-21 08:32
I confirm the suggested fix here is working for us too https://github.com/Adyen/adyen-web/issues/2818#issuecomment-2357725185

**Comment by ribeiroguilherme** [comment] 2024-10-31 13:36
@tlenclos @bramdebouvere we released v6.5.0 which contains a fix for this issue.  Could you guys test it out and confirm the the issue is fixed? 🙏

**Comment by bramdebouvere** [comment] 2024-11-04 19:05
@ribeiroguilherme Just tested this, seems to fix the issue here. Thanks!

**Comment by ribeiroguilherme** [comment] 2024-11-05 16:06
@bramdebouvere thanks for checking it and for reporting the issue. I will close this thread. Cheers!

**Closed by ribeiroguilherme** 2024-11-05 16:06 UTC
Labels: Needs more info, Fixed: awaiting confirmation
