### ISSUE TITLE
Reduce Bundle Size (excluding unused i18n and payment methods?)

### ISSUE THREAD

**Issue by JStonevalley** [Adyen/adyen-web#337] opened 2020-09-24 07:04 UTC
**Is your feature request related to a problem? Please describe.**
The bundle size of the SDK is huge. There seems to be lots of i18n in the bundle that I will never use. As well as functionality for unused payment methods.

**Describe the solution you'd like**
It would be great if it was possible to include only the languages and paymentmethods that you need in the bundle to reduce the size.

**Describe alternatives you've considered**
Same as above

**Additional context**
-

**Comment by marcperez** [comment] 2020-09-24 08:37
Hi @JStonevalley,

Thanks for reaching! That's indeed something we want to improve and is in our roadmap and will be part of an upcoming major release.

**Comment by JStonevalley** [comment] 2020-09-24 09:04
Ok so there are no such options available at the moment?
Is it part of the next major release or is it further down the road?

**Comment by marcperez** [comment] 2020-09-28 09:31
Hi @JStonevalley,

Unfortunately, we don't have a timeline at this point, but it's something we are prioritizing for the next major version.

**Comment by nachogarcia** [comment] 2020-11-11 12:22
It might be great to have also a ES6 build so we can use it for modern browsers and reduze some size.

**Comment by steffenmllr** [comment] 2020-11-25 12:22
`121.5kB Minified + Gzipped` is more than all our other vendor packages combined https://bundlephobia.com/result?p=@adyen/adyen-web@3.18.2 - would be great if you could prioritize this.

**Comment by matsinfiltratingvy** [comment] 2021-02-17 11:17
```
Bundle without adyen: 232 KB (76 KB gzipped)
Bundle with adyen: 856 KB (227 KB gzipped)
```

So our entire webapp is about 200 KB with all code, css, libraries etc. Until we import adyen-web and it explodes in size. Given the millions of times this code is downloaded each day, you really should spend some effort on making it smaller.

**Comment by marcperez** [comment] 2021-02-17 11:54
Hi @matsinfiltratingvy,

Thank you for your comment. We're aware of this and currently working on a solution. 
The first step will include dynamically loading the language translation files and it will be released as part of our next major version (`v4.0.0`, which is planned for release in the next few weeks). After that, we're also planning on a similar solution for the different payment methods included in the library.

Please, let us know if you have any specific suggestions or feedback on this. Hope this helps!

**Comment by matsinfiltratingvy** [comment] 2021-02-17 14:21
Hi, thanks for getting back to me.

One thing could be to write it in such a way that it's easier to tree-shake/only include what's being used. Right now one passes in a string for which component to be rendered, which means you have to look it up dynamically and thus have everything in the bundle.

Instead, if we had to pass in the specific component, we could make sure to only include the needed ones in our bundle. Of course, this makes the outward facing API not as smooth to use since not everything is included by default.

```
// Now:
import AdyenCheckout from '@adyen/adyen-web'
const config = {...}
const adyenCheckout = new AdyenCheckout(config);
adyenCheckout.create('card', {....}).mount("#id");

// ===================
// vs maybe something like this
import AdyenCheckout from '@adyen/adyen-web/checkout'
import Card from '@adyen/adyen-web/components/card'
import PayPal from '@adyen/adyen-web/components/paypal'

const config = {...}
const adyenCheckout = new AdyenCheckout(config);
if (selection === 'card') {
    adyenCheckout.create(Card, {....}).mount("#id");
} else if (selection == 'paypal') {
    adyenCheckout.create(PayPal, {....}).mount("#id");
}

// or maybe some changes to the API when it's not stringly typed, like
new Card(adyenCheckout, {...}).mount('#id');

// ===============
// or instead if you still want the API to be the same, maybe one could pass in the available components in the config
// here one could also maybe have a "import AllComponents from @adyen/adyen-web/components", such that people not caring about bundle size or just want it up and running have an easier way
import AdyenCheckout from '@adyen/adyen-web/checkout'
import Card from '@adyen/adyen-web/components/card'
import PayPal from '@adyen/adyen-web/components/paypal'

const config = {
   ...,
  availableComponents: [Card, PayPal]
}
const adyenCheckout = new AdyenCheckout(config);
adyenCheckout.create('card', {....}).mount("#id");

```

Just some suggestions, details aren't so important, the point is to be able to import only what's needed.
Same goes for locales. Instead of you bundling everything and choosing texts based on a parameter, one could just provide the texts directly. So something similar to this: https://docs.adyen.com/online-payments/components-web/localization-components#customize-localization
But instead of making a custom, one just pulls in the wanted texts.

```
import AdyenCheckout from '@adyen/adyen-web/checkout'
import English from '@adyen/adyen-web/types//language/locales/en_En'
import Norwegian from '@adyen/adyen-web/types//language/locales/no_NO'

const config = {
   ....,
   translation: lang == 'no' ? Norwegian : English;
}
etc
```

**Comment by herecydev** [comment] 2021-07-19 07:40
@marcperez any further update on this, Adyen is by far the biggest offender for us right now. @matsinfiltratingvy suggestion would work well for us!

**Comment by marcperez** [comment] 2021-08-02 07:46
> @marcperez any further update on this, Adyen is by far the biggest offender for us right now. @matsinfiltratingvy suggestion would work well for us!

Hi @herecydev,

Thanks for bumping this. From v4.0.0, when using the ES Module version (through NPM), we currently dynamically load the language files. This should reduce the size of the library from the original 140KB to around 80KB.
We understand size is an important point of improvement and we will continue our efforts in this direction, for example, exploring how we can dynamically load payment methods as well in the future.

Hope this helps and we're always happy to hear of any idea or feedback, thanks! 

Also, thanks @matsinfiltratingvy for the great ideas above!

**Comment by herecydev** [comment] 2021-08-23 06:07
@marcperez I've also notice that there is a dependency on preact. That's somewhat weird, as we are running within the context of React, so we're now having to use 2 frontend libraries.

However if you just relied on react, then consumers can make the decision whether to use `preact/compat` and switch to using preact. This is the only library where I've seen a reliance on preact like this.

**Comment by marcperez** [comment] 2021-10-01 10:07
> @marcperez I've also notice that there is a dependency on preact. That's somewhat weird, as we are running within the context of React, so we're now having to use 2 frontend libraries.
> 
> However if you just relied on react, then consumers can make the decision whether to use `preact/compat` and switch to using preact. This is the only library where I've seen a reliance on preact like this.

Hi @herecydev. Thanks for your comment. Indeed, we do use preact for our components (and not React). One of the considerations on this choice is the small size of the preact dependency (around 3KB). 
Since this library should work independently of the framework used on the application where it runs, we can't rely on the consumer using React (it could be Vue, Angular, or no framework at all). 

Hope this clarifies and thanks again for the feedback!

**Comment by kholiavko-roman** [comment] 2022-05-11 22:17
The bundle size was increased even more in the last versions 😔
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/16399378/167956575-d1cd9420-ef54-4395-afcd-8d58afdda2f9.png">

**Comment by m1aw** [comment] 2022-05-12 08:49
@kholiavko-roman which version are you using? 
Has mentioned in #1343 we now provide a modern version for everyone that doesn't need to rely on polyfills for browser compatibility.

**Comment by aralroca** [comment] 2022-07-12 15:20
E-commerce has to go fast, Adyen slows us down, it is currently the largest piece of JavaScript in our project, would it be possible to dedicate to reduce this size? Thank you.

![image](https://user-images.githubusercontent.com/13313058/178467007-4992c2a3-8cdd-4273-bb18-8f50a23036b1.png)

**Comment by m1aw** [comment] 2022-07-12 15:28
@aralroca have you tried using the bundle available in `lib/dist/es.modern/`?

**Comment by kholiavko-roman** [comment] 2022-07-12 15:42
@m1aw I am using 5.15.0
How we can use a `lib/dist/es.modern/` version of lib if we just using just the npm package?

**Comment by m1aw** [comment] 2022-07-12 15:53
@kholiavko-roman Depends a bit on the bundler that you are using, some version of webpack/rollup support different ways of doing this.
In principal you should be able to just prefix your imports with `modern`, like:
```
import AdyenCheckout from '@adyen/adyen-web/modern/';
```
If this doesn't work you can try to point to the full path: `./dist/es.modern/index.js`

**WARNING: This version doesn't come with polyfills.** So if you targeting specific browsers versions like IE11 you will need to provide your own polyfills.

**Comment by carly-cloud** [comment] 2022-10-04 13:51
Adyen is already working on it and provide a workaround if needed: [https://github.com/Adyen/adyen-web/issues/337#issuecomment-1181939939](https://github.com/Adyen/adyen-web/issues/337#issuecomment-1181939939)

**Comment by fahu** [comment] 2023-01-16 15:09
We are also struggling with huge bundle size caused by the Adyen dependency. Especially with payments user loading time is super important and is right now our biggest pain point with the Adyen web components.

**Comment by RyanONeill1970** [comment] 2023-02-16 10:37
Apologies for the off topic point, @aralroca can you tell me how you prepped the js file size / names to go into that Voronei map?

**Comment by m1aw** [comment] 2023-02-16 11:19
@RyanONeill1970 it's part of [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer), hope that helps.

**Comment by welschmoor** [comment] 2023-06-19 09:49
Any updates on this?

**Comment by holgerh** [comment] 2023-06-19 11:48
This is very important for us. The modern version adds 216KB (gzipped) to our checkout. That is by far the greatest download and we would very, very much appreciate to be able to exclude not needed payment-methods and languages from the bundle.

**Comment by sponglord** [comment] 2023-07-04 10:52
Closing this issue.
FYI - we are in the process of planning adyen-web v6. One of the man features of this will be a reduced bundle size (including a rethink on how we include the language files)

**Comment by MakChan** [comment] 2023-10-17 15:09
@sponglord Is there a timeline for v6?

**Comment by sponglord** [comment] 2023-10-18 09:50
@MakChan - we are aiming for the end of November. However this is a loose deadline and could be subject to change, particularly as the end of the year represents Peak season, which can affect our release schedule.

**Comment by gorkemcnr** [comment] 2023-11-03 23:09
I have also experienced the same issue. To avoid to load unused locales, I have come up with following workaround with using Webpack IgnorePlugin  which works pretty decent. 

Add the following code part into your webpack.config.js with adding locales to AdyenWebExcludedLocales that you want to exclude them from bundle

```js
//webpack.config.js

const AdyenWebExcludedLocales = new Set([
    'cs-CZ',
    'el-GR',
    'es-ES',
]);

const adyenIgnorePluginConfig = new webpack.IgnorePlugin({
    checkResource(resource, context) {
        if (!/@adyen\/adyen-web\/dist\/es/.test(context)) return false

        // Extract the filename from the resource path
        const parts = resource.split('/')
        const filenameWithExtension = parts[parts.length - 1]

        // Remove the file extension
        const filename = filenameWithExtension.replace(/\.[^/.]+$/, '')

        return AdyenWebExcludedLocales.has(filename)
    },
})

module.exports = {
  plugins: [adyenIgnorePluginConfig],
};


```

**Comment by carly-cloud** [comment] 2024-01-15 14:08
any news here?

**Comment by ribeiroguilherme** [comment] 2024-01-16 09:38
Hey @carly-cloud ,

We are currently working on the new major version which will reduce the bundle size. There are some details to wrap up still, but we are aiming for the end of February hopefully.

**Comment by ribeiroguilherme** [comment] 2024-03-08 10:07
Hey @fahu ,

We do have some updates 😄  we are working on it and wrapping up the final details. We also released an alpha version on `npm`, but that is mainly for our internal teams to test the changes. There is no migration guide nor tutorial explaining how to try the alpha in case you are interested, although our team is also working on that. 

In the upcoming weeks we will do a release candidate along with the migration guide/documentation 🙏 

As we are performing tests now, could you (and also the other people that are following this thread) share more about your  web app tech stack? Ex: webpack 4 or 5; vite; UI framework (react, svelte, etc); Nextjs, Nuxtjs, etc. These details can help us make sure we will test for different use-cases.

**Comment by fahu** [comment] 2024-03-08 10:28
Thanks for the update @ribeiroguilherme :) Looking forward to try it out! Tech stack is Angular 16 (probably 17 soonish) + Webpack 5.

**Comment by juliavanmourik** [comment] 2024-04-22 17:36
Thanks @ribeiroguilherme ! I've been checking this thread for a while now. Looking forward to the release as well. We're on nuxt3/vite

**Comment by ribeiroguilherme** [comment] 2024-04-24 13:09
Thanks for sharing guys - we will make sure to test the alpha version on these setups 🙏

**Comment by brunolopesr-dft** [comment] 2024-05-22 10:15
Here we are using [Vite](https://vitejs.dev) to bundle a React app for our checkout

![image](https://github.com/Adyen/adyen-web/assets/156701703/b0f490d6-48b4-48ad-ae0d-7bed13a408f3)

It's a huge bundle size included in our app to use only the secured fields component and pt-BR locale.

Waiting for 6.0.0 stable release to land, hopes this will fix the problem.

**Comment by camil-adyen** [comment] 2024-06-25 09:01
Hi all! 

A BETA version of Web v6 is now available on Github. Feel free to take a look and give us feedback! We aim to release the official v6 in the coming weeks. More information can be found [here](https://github.com/Adyen/adyen-web/releases/tag/v6.0.0-beta.0).

**Comment by sponglord** [comment] 2024-07-24 14:33
The major release, `v6.0.0`, was launched today!
See the documentation here:
- [release notes](https://docs.adyen.com/online-payments/release-notes/#releaseNote=2024-07-24-web-componentsdrop-in-6.0.0)
- [migration guide](https://docs.adyen.com/online-payments/update-your-integration/migrate-to-web-v6/)

**Closed by sponglord** 2024-07-24 14:33 UTC
Labels: Enhancement, Bundle size, v6
