### ISSUE TITLE
Using adyen-web in capacitor on IOS

### ISSUE THREAD

**Issue by joepjoosten** [Adyen/adyen-web#272] opened 2020-09-11 07:54 UTC
Using adyen-web in capacitor on IOS results in sending the request to "https://checkoutshopper-test.adyen.com/checkoutshopper/" with the "origin" header set as "capacitor://appname.com".

This results in "Invalid client key or unknown origin". Probably because of adyen not accepting "capacitor://" as a valid scheme for the origin. (it accepts "capacitor://appname.com" in the "allowed origin" on your account page of adyen, but it's not working).

We could use a plugin for capacitor for native HTTP requests, but then we need to be able to overwrite the "default" fetch method used in several locations.

- Is this a use case adyen-web wants to support? 
- Is it maybe a bug in adyen for not accepting "capacitor://appname.com" as "allowed origin"?

@marcperez?

**Comment by marcperez** [comment] 2020-09-11 09:41
Hi @joepjoosten,

Please, make sure you are using the new [Client Keys](https://docs.adyen.com/development-resources/client-side-authentication#get-your-client-key) (or [migrate from origin keys to client keys](https://docs.adyen.com/development-resources/client-side-authentication/migrate-from-origin-key-to-client-key)). As long as you add your origin (`capacitor://appname.com`) in the list of allowed origins, the requests should be accepted.

Hope that helps!

Cheers!

**Comment by marcperez** [comment] 2020-09-11 09:44
Closing the issue, feel free to reopen if you need any more help! Cheers!

**Closed** 2020-09-11 09:43 UTC
Labels: enhancement

**Comment by hrietman** [comment] 2020-09-11 11:02
Hi Marc, thanks for the quick response! We are using the client-key and we added the capacitor to the allowed origins. It all works well on Android and web (both using the same client-key and http://localhost as origin) From Adyen support I got the message back that no other than http/https is supported. Which could clarify the issue; what are you thoughts on this?

**Comment by joepjoosten** [comment] 2020-09-11 11:57
Hi @marcperez,

What @hrietman  is saying is correct. Support is saying that they only support http/https as allowed origins for the drop-in integration. Should we assume this project is only for web based clients? (so not to be used in the webview of ios on a capacitor app)

**Comment by marcperez** [comment] 2020-09-11 12:35
Hi @joepjoosten/@hrietman,

Since this seems to be an issue with the integration and not a bug on the library itself, let’s communicate through the support channel. 

Cheers!
